### ISSUE TITLE
Remove reference to outdated Gatsby plugin

### ISSUE THREAD

**Issue by w3bdesign** [thundermiracle/gatsby-startbootstrap-agency#10]
Gatsby-plugin-prefetch-google-fonts is archived, no longer updated and vulnerable.

Please see https://npmjs.com/advisories/1550

**Comment by thundermiracle** [comment]
I think you're absolutely right. Thank you very much!
I tried a lot and by https://web.dev/ I found out that using `gatsby-plugin-prefetch-google-fonts` to prefetch the fonts is the fastest way.
I'll switch it to typeface soon.

**Comment by w3bdesign** [comment]
> 
> 
> I think you're absolutely right. Thank you very much!
> I tried a lot and by https://web.dev/ I found out that using `gatsby-plugin-prefetch-google-fonts` to prefetch the fonts is the fastest way.
> I'll switch it to typeface soon.

Not sure if you need to install it manually, as according to the Typeface Github README, Gatsby is already setup to use Typefaces:

"Many tools built with webpack such as Gatsby and Create React App are already setup to work with Typefaces."

**Comment by thundermiracle** [comment]
@w3bdesign 
I think for using font MontSerrat, install `typeface-montserrat` and import it in `gatsy-browser.js` is necessary.
Any other solution?

**Comment by w3bdesign** [comment]
@thundermiracle 

I would probably import it in gatsby-ssr.js as well.

That way the font will match at initial load as well as after load. That way you won't get a FOUC (Flash Of Unstyled Content) where you see the default font for a second or two and then the Montserrat font loads.

However, this is just a theory and untested by me, so feel free to try it out yourself!

**Comment by thundermiracle** [comment]
@w3bdesign 
Great! Thanks for your advice.

**Comment by w3bdesign** [comment]
@thundermiracle 

You may be interested in https://github.com/thundermiracle/gatsby-startbootstrap-agency/pull/12
