### ISSUE TITLE
remove an item from section menu

### ISSUE THREAD

**Issue by cheroliv** [thundermiracle/gatsby-startbootstrap-agency#14]
Hello
I try to remove the team item section from sections menu.
I can't find where to search to start.
Can I get an hint.
Thanks

**Comment by thundermiracle** [comment]
>I try to remove the team item section from sections menu

To hide `Team` section in menu, just delete the `anchor` in `Team.xx.md`.
To delete the `Team` section part in landing-page, the simplest way is deleting the `Team` component's export part [here ](https://github.com/thundermiracle/gatsby-startbootstrap-agency/blob/af4340e6a975a2cce8758dc300e8965a115f8c58/src/views/Sections/index.js#L5).

**Comment by cheroliv** [comment]
Thanks for your response it works!
