### ISSUE TITLE
Problem with default language.

### ISSUE THREAD

**Issue by demetrio** [thundermiracle/gatsby-startbootstrap-agency#4]
Hello! I download your template and I try to change the default language to Japanese (ja) in `config/site.js` and when testing the page this happened:

```javascript
module.exports = {
  title: "Gatsyby Startbootstrap Agency",
  keywords: [
    "gatsby",
    "gatsbyjs",
    "landing page",
    "landing",
    "i18n",
    "eslint",
    "bootstrap",
    "startbootstrap-agency",
  ],
  description: "gatsby version of startbootstrap-agency with i18n support.",
  author: "thundermiracle",
  trackingId: "UA-119418003-5",
  defaultLang: "ja",
  langTextMap: {
    en: "English",
    ja: "日本語",
  },
};
```
<img width="1788" alt="Screenshot 2020-05-08 at 16 40 07" src="https://user-images.githubusercontent.com/23102567/81416927-b8aa5700-914a-11ea-92f0-5bbb50c0a33d.png">

Both texts (in English and Japanese) are displayed at the same time in the NavBar. Also, if you try to change the language, an error will be displayed.

<img width="1163" alt="Screenshot 2020-05-08 at 16 40 34" src="https://user-images.githubusercontent.com/23102567/81417080-ee4f4000-914a-11ea-86fd-3750a8d866b4.png">

**Comment by thundermiracle** [comment]
That's because there's no `xxxx.en.md` exists in `/content` folder. 
As you changed default language to ja, all `xxxx.md` are considered as definitions for Japanese as well as all `xxxx.ja.md`, so the system crashed.
I'll add `.en` to all English markdown files and the problem will be gone.

**Comment by demetrio** [comment]
Yes, sorry, hours later I realized that was the problem, but I was too late and I forgot to write here.
Right now I'm trying to get the page to detect the browser language to set that language as default. If I succeed, do you want a pull request to add it to the repository?

**Comment by thundermiracle** [comment]
Yes, please. I’m looking forward to your PR.

**Comment by demetrio** [comment]
Okay! If I get it, I'll open a pull-request. I proceed to close this. Have a nice day!
